### ISSUE TITLE
Windows and Linux light wallet not working.

### ISSUE THREAD

**Issue by utkarsh009** [iotaledger/wallet#1002]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

- [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
- [x] I confirm that this is an issue with the wallet, not IRI
- [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
- [x] I confirm that this is not an issue related to stolen/lost funds
- [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
- [x] I confirm that this issue is present on the latest version of the wallet

### Steps to Reproduce

1. Download and install Windows wallet/run the iota binary from downloaded tarball in linux
2. Login using seed and click on attach address

**Expected behavior:** [What you expected to happen]
Address should have been attached and the bundle should have shown confirm.
**Actual behavior:** [What actually happened]
Upon trying multiple times, I could create a transaction (for attaching the address) only ones and even that is pending. Here's a [link](https://thetangle.org/address/RRUZHOTCLWFKVHFNKXMEVNTDLVYG9DWLWOFWXFFGFLLDKZRQXCAFRUEVAY9CUGXIJRJMFJOBKCRKYPOWX). So far, I've tried on my desktop (windows) and laptop (linux, windows). I've also tried changing the node configuration. Upon selecting http://iota.bitfinex.com:80, it displays invalid response. Upon selecting any other node, it just keeps trying to attach to tangle.

### System Configuration
* Desktop
  * AMD FX8350 (8-core processor @4GHz.)
* Laptop
  * Intel core i5-6300HQ (4-core processor @2.3GHz.)

### Versions

[OS Version]
1.``` [utkarsh@valkyr extra]$ uname -a```
```Linux valkyr 4.14.8-1-ARCH #1 SMP PREEMPT Wed Dec 20 21:27:44 UTC 2017 x86_64 GNU/Linux```
2. Windows 10

[Wallet Version]
2.5.6

**Comment by utkarsh009** [comment]
I just tried attaching a few more addresses and here are the results:
![h2khya4](https://user-images.githubusercontent.com/17116349/34907597-3b0e20f8-f8a7-11e7-8524-67c1795ecb79.png)
![h2kigyg](https://user-images.githubusercontent.com/17116349/34907598-3b5cab38-f8a7-11e7-9873-f565b5c418f6.png)
![h2kikz2](https://user-images.githubusercontent.com/17116349/34907599-3baeeb00-f8a7-11e7-8dd1-89d863c0122b.png)
![h2kiwrux](https://user-images.githubusercontent.com/17116349/34907600-3c515098-f8a7-11e7-882f-011e5147042f.png)
![h2kiyvl](https://user-images.githubusercontent.com/17116349/34907601-3c9f7a52-f8a7-11e7-9339-9eb035d36c88.png)
![h2kjekp](https://user-images.githubusercontent.com/17116349/34907602-3ce9c9d6-f8a7-11e7-9b0a-46d41aa87077.png)
![h2kjtvy](https://user-images.githubusercontent.com/17116349/34907603-3d303e70-f8a7-11e7-81c8-d26b6e5f1d00.png)

**Comment by wonkytonky** [comment]
looked like most  public nodes was beeing dossed..  all day.   
try again now.. i just got my tx confirmed.. took a few reattachments

**Comment by WurstCommander** [comment]
yeah, yesterday I spend HOURS with getting transactions transformed, I found a node js console wallet which was much better than the real one.

my wallet was totally confused because I had multiple transactions which weren't confirmed and it's just a pain in the ass to find all transactions and their reattached successors in the real wallet. It's ridiculous how bad it is.

https://github.com/MichaelSchwab/iota-commandline-wallet

I used this one (with POW proxy) to get all address with their bundles and confirmed them one by one, took many hours, but finally, the "private key already blah blah coin is spent" error is gone.

Yesterday IOTA was really disheartening, the nodes are slow, the wallet is super bad, I reattached and promoted so many hours, it was the worst experience with any coin for me. I really hope the new wallet doesn't this things "under the hood". 

Any way with a little nodejs knowledge the commandline-wallet is pretty cool because you get feedback and not just a rotating icon and "request failed!"

**Comment by utkarsh009** [comment]
@WurstCommander I tried using that wallet and here are the results:
- When the node was set to `http://node01.iotatoken.nl:14265`:
```
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js ShowDB
INDEX: 0 ADR: RRUZHOTCLWFKVHFNKXMEVNTDLVYG9DWLWOFWXFFGFLLDKZRQXCAFRUEVAY9CUGXIJRJMFJOBKCRKYPOWXRVNIJRJFD Balance: 0 Status: published
INDEX: 1 ADR: PCNDVBQXCGWDHLQQMXIRNQNVILKXRXUAKK9YBMLIEMA9ZVCUHZWTGWEWACODBYUWRFAFQADJBUMLNQMOBUVGASMWRB Balance: 0 Status: published
INDEX: 2 ADR: MFDWRYMJZB9IOWMJZNQJ9KJTALYJIZBNLMCHPRZMI9ZZVZZAUDHMZTUKEQAJLNSPYFVZLTV9RQSFNTTTCTKJLKOTEC Balance: 0 Status: published
INDEX: 3 ADR: JPWZWLUPMXWAWZPNTMNDFHHNYAUVGNJBCB9RZPQGZVWPRRWMCNATGQRU9LRKKZFCYFZOQ9GDJHCMUGOHDZNQHSTGMA Balance: 0 Status: published
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js Sync
INDEX: 0 ADR: RRUZHOTCLWFKVHFNKXME.... Balance: 0 Status: published
INDEX: 1 ADR: PCNDVBQXCGWDHLQQMXIR.... Balance: 0 Status: published
INDEX: 2 ADR: MFDWRYMJZB9IOWMJZNQJ.... Balance: 0 Status: published
INDEX: 3 ADR: JPWZWLUPMXWAWZPNTMND.... Balance: 0 Status: published
INDEX: 4 ADR: TAOUABJUYTXCNKCSVEHQ.... Balance: 0 Status: new
INDEX: 5 ADR: CQRBWCHUSQQWFHIKBJWU.... Balance: 0 Status: new
INDEX: 6 ADR: BQDU9EBAO9GDFFVBYKKI.... Balance: 0 Status: new
INDEX: 7 ADR: TUIEWQHUOPYSXJFOY9YC.... Balance: 0 Status: new
INDEX: 8 ADR: GFKAMUJMLXRKWPMNKKTQ.... Balance: 0 Status: new
INDEX: 9 ADR: ULSKENXEXNEQXWOEKUNK.... Balance: 0 Status: new
INDEX: 10 ADR: WHGQISFLCYVPGJLBVSRD.... Balance: 0 Status: new
INDEX: 11 ADR: SUVOUMXTASLNFJPVYG9C.... Balance: 0 Status: new
INDEX: 12 ADR: LMYMCKWZZQTYTNHQEDOG.... Balance: 0 Status: new
INDEX: 13 ADR: OUNTAOVSGYISYIFALIGV.... Balance: 0 Status: new
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js Replay JPWZWLUPMXWAWZPNTMNDFHHNYAUVGNJBCB9RZPQGZVWPRRWMCNATGQRU9LRKKZFCYFZOQ9GDJHCMUGOHDZNQHSTGMA
{"replayedBundles":[],"status":"ok"}
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js Transfer JPWZWLUPMXWAWZPNTMNDFHHNYAUVGNJBCB9RZPQGZVWPRRWMCNATGQRU9LRKKZFCYFZOQ9GDJHCMUGOHDZNQHSTGMA 0
{ status: "error", message: "Transfer failed. Request Error: COMMAND attachToTangle is not available on this node"}
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js Replay JPWZWLUPMXWAWZPNTMNDFHHNYAUVGNJBCB9RZPQGZVWPRRWMCNATGQRU9LRKKZFCYFZOQ9GDJHCMUGOHDZNQHSTGMA
{"replayedBundles":[],"status":"ok"}
```
- When the node was set to `http://iota.bitfinex.com:80`:
```
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js Transfer JPWZWLUPMXWAWZPNTMNDFHHNYAUVGNJBCB9RZPQGZVWPRRWMCNATGQRU9LRKKZFCYFZOQ9GDJHCMUGOHDZNQHSTGMA 0
{ status: "error", message: "Transfer failed. Invalid Response: I'm depressed, leave me be.
"}
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js Replay RRUZHOTCLWFKVHFNKXMEVNTDLVYG9DWLWOFWXFFGFLLDKZRQXCAFRUEVAY9CUGXIJRJMFJOBKCRKYPOWXRVNIJRJFD
(node:1893) UnhandledPromiseRejectionWarning: Error: Invalid Response: I'm depressed, leave me be.

    at Object.invalidResponse (/extra/iota-commandline-wallet/node_modules/iota.lib.js/lib/errors/requestErrors.js:5:12)
    at makeRequest.prepareResult (/extra/iota-commandline-wallet/node_modules/iota.lib.js/lib/utils/makeRequest.js:283:24)
    at exports.XMLHttpRequest.request.onreadystatechange (/extra/iota-commandline-wallet/node_modules/iota.lib.js/lib/utils/makeRequest.js:71:25)
    at exports.XMLHttpRequest.dispatchEvent (/extra/iota-commandline-wallet/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/extra/iota-commandline-wallet/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/extra/iota-commandline-wallet/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
(node:1893) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1893) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
- When the node was set to `http://eugene.iotasupport.com:14999`:
```
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js Replay RRUZHOTCLWFKVHFNKXMEVNTDLVYG9DWLWOFWXFFGFLLDKZRQXCAFRUEVAY9CUGXIJRJMFJOBKCRKYPOWXRVNIJRJFD
BUNDLE: GZZZJGECECQ9OBVOCIRGICBDVYH9LZKGGSUXECUCVXHXJWWDOICADKQMWZDJCFNVJJEUHRFKKKLGIIPZZ
REPLAY COUNT: 1 CONFIRMED Tx IN BUNDLE: 0 UNCONFIRMED Tx: 1 TAIL: G9DAPGSUKEFRTOJAYTOMXSEXATSJLRUUEXTXCFSPSONAXQHYLNRYPSKJIPTJGWGOXVKQDNIJXNGVZ9999 Funding: true
Replaying
REPLAY COUNT: 1 CONFIRMED Tx IN BUNDLE: 0 UNCONFIRMED Tx: 1 TAIL: G9DAPGSUKEFRTOJAYTOMXSEXATSJLRUUEXTXCFSPSONAXQHYLNRYPSKJIPTJGWGOXVKQDNIJXNGVZ9999 Funding: true
{ status: "error", message: "Replay failed. Request Error: COMMAND attachToTangle is not available on this node"}
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js Transfer JPWZWLUPMXWAWZPNTMNDFHHNYAUVGNJBCB9RZPQGZVWPRRWMCNATGQRU9LRKKZFCYFZOQ9GDJHCMUGOHDZNQHSTGMA 0
{ status: "error", message: "Transfer failed. Request Error: COMMAND attachToTangle is not available on this node"}
```
Looks like none of the nodes are letting me attach the addresses to the tangle!

**Comment by utkarsh009** [comment]
I also tried using `tor` and `proxychains` but I still get the same error!
```
[utkarsh@valkyr iota-commandline-wallet]$ proxychains node my-wallet.js Replay PCNDVBQXCGWDHLQQMXIRNQNVILKXRXUAKK9YBMLIEMA9ZVCUHZWTGWEWACODBYUWRFAFQADJBUMLNQMOBUVGASMWRB
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  eugene.iotasupport.com:14999  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  eugene.iotasupport.com:14999  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  eugene.iotasupport.com:14999  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  eugene.iotasupport.com:14999  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  eugene.iotasupport.com:14999  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  eugene.iotasupport.com:14999  ...  OK
BUNDLE: DHBXCNUAXSZEEEWJN9FLGKNXXRWHKHNQ99VH9AYWEBNAUKQLZUFHGYZSNINKDTPHHKQGWJKVOZUAIFZVD
REPLAY COUNT: 1 CONFIRMED Tx IN BUNDLE: 0 UNCONFIRMED Tx: 1 TAIL: VZGX9GNRPAM9QEHWWHYABCHTNRVEKJFHF9MFDHOSROCJ9OZPHNAUTYUSADJT9TSKNFFNAEMPVQDTA9999 Funding: true
Replaying
REPLAY COUNT: 1 CONFIRMED Tx IN BUNDLE: 0 UNCONFIRMED Tx: 1 TAIL: VZGX9GNRPAM9QEHWWHYABCHTNRVEKJFHF9MFDHOSROCJ9OZPHNAUTYUSADJT9TSKNFFNAEMPVQDTA9999 Funding: true
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  eugene.iotasupport.com:14999  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  eugene.iotasupport.com:14999  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  eugene.iotasupport.com:14999  ...  OK
{ status: "error", message: "Replay failed. Request Error: COMMAND attachToTangle is not available on this node"}
```
BTW, even if it worked that way, I wouldn't use it because even after trying multiple proxies, only a few work and that too for a small amount of time!
I'd like to hear from the dev team. Logging in/Reattaching takes a long time and my connection is fast enough, so that's not the bottleneck.

**Comment by utkarsh009** [comment]
I just found out that only a few nodes allow for PoW on that node itself. The same can be found [here](iota.dance/nodes)
```
[utkarsh@valkyr iota-commandline-wallet]$ node my-wallet.js Transfer JPWZWLUPMXWAWZPNTMNDFHHNYAUVGNJBCB9RZPQGZVWPRRWMCNATGQRU9LRKKZFCYFZOQ9GDJHCMUGOHDZNQHSTGMA 0
BUNDLE: IYJUYETVYGWVPXEVBYLFIBEFHDRJXTYP9UWWLITYHTDCT9IGDZOBACEXPCQGFUCRIWRJDLOWYZVJFNH9D
TRANSACTION: CZQYMTAVGJZCLPAUACNGBFQW9UNMKZTTYCMYRZSGG9MCJUAHDDZPD99JTBSYUFMFLPRPADPJJE9Q99999
{"bundle":"IYJUYETVYGWVPXEVBYLFIBEFHDRJXTYP9UWWLITYHTDCT9IGDZOBACEXPCQGFUCRIWRJDLOWYZVJFNH9D","tailTransaction":"CZQYMTAVGJZCLPAUACNGBFQW9UNMKZTTYCMYRZSGG9MCJUAHDDZPD99JTBSYUFMFLPRPADPJJE9Q99999","status":"ok"}
```
But I still haven't got a confirmation!

**Comment by utkarsh009** [comment]
No confirmation yet, even with `proxychains`! :sob: 
```
[utkarsh@valkyr iota-commandline-wallet]$ proxychains node my-wallet.js Replay RRUZHOTCLWFKVHFNKXMEVNTDLVYG9DWLWOFWXFFGFLLDKZRQXCAFRUEVAY9CUGXIJRJMFJOBKCRKYPOWXRVNIJRJFD
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
BUNDLE: GZZZJGECECQ9OBVOCIRGICBDVYH9LZKGGSUXECUCVXHXJWWDOICADKQMWZDJCFNVJJEUHRFKKKLGIIPZZ
REPLAY COUNT: 3 CONFIRMED Tx IN BUNDLE: 0 UNCONFIRMED Tx: 3 TAIL: UYTZJONOTJWYXYBVONUZTUYQVULRLNMWIBKAAGWVLVAEVVZJNFVQWUIWWSFEDSS9VEOEBFKGFDEZZ9999 Funding: true
Replaying
REPLAY COUNT: 3 CONFIRMED Tx IN BUNDLE: 0 UNCONFIRMED Tx: 3 TAIL: UYTZJONOTJWYXYBVONUZTUYQVULRLNMWIBKAAGWVLVAEVVZJNFVQWUIWWSFEDSS9VEOEBFKGFDEZZ9999 Funding: true
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  138.201.147.235:80  ...  iotanode.us:443  ...  OK
{"replayedBundles":["GZZZJGECECQ9OBVOCIRGICBDVYH9LZKGGSUXECUCVXHXJWWDOICADKQMWZDJCFNVJJEUHRFKKKLGIIPZZ"],"status":"ok"}
```

**Comment by WurstCommander** [comment]
for non-pow nodes (which seem to be nearly all...) I used iotaproxy-master

**Comment by utkarsh009** [comment]
@WurstCommander I've created a GUI for that wallet. You can find it right [here](https://github.com/utkarsh009/heliota). Do give it a try. Thanks for the info about iotaproxy. I'll check that out.

**Comment by utkarsh009** [comment]
I am closing this issue because some of the transactions are now getting confirmed using [Heliota Wallet](https://github.com/utkarsh009/heliota/). See [this](https://thetangle.org/address/RRUZHOTCLWFKVHFNKXMEVNTDLVYG9DWLWOFWXFFGFLLDKZRQXCAFRUEVAY9CUGXIJRJMFJOBKCRKYPOWX).

**Comment by WurstCommander** [comment]
Awesome, you did what I was too lazy for :-)
