### ISSUE TITLE
Debian 9: com.sanityinc.jargs.CmdLineParser$UnknownOptionException: Unknown option '--headless'

### ISSUE THREAD

**Issue by porunov** [iotaledger/wallet#114]
Hello, 

I tried to install IOTA wallet on Debian 9 but without success. Tried several times but the installation is too complicated.

I tried to install it with nodejs 6 and nodejs 8.

Here is the error I get when I try to run the wallet:
```
06/14 00:44:30.752 [main] ERROR com.iota.iri.IRI - CLI error: 
com.sanityinc.jargs.CmdLineParser$UnknownOptionException: Unknown option '--headless'
	at com.sanityinc.jargs.CmdLineParser.parse(CmdLineParser.java:556) ~[iri.jar:na]
	at com.sanityinc.jargs.CmdLineParser.parse(CmdLineParser.java:510) ~[iri.jar:na]
	at com.iota.iri.IRI.validateParams(IRI.java:126) [iri.jar:na]
	at com.iota.iri.IRI.main(IRI.java:51) [iri.jar:na]
06/14 00:44:30.778 [main] INFO  com.iota.iri.IRI - Usage: java -jar IRI-1.2.1.jar [{-n,--neighbors} '<list of neighbors>'] [{-p,--port} 14600] [{-c,--config} 'config-file-name'] [{-u,--udp-receiver-port} 14600] [{-t,--tcp-receiver-port} 15600] [{-d,--debug} false] [{--testnet} false][{--remote} false][{--remote-auth} string][{--remote-limit-api} string]
Process exited with status 0
```

Steps to reproduce:
1) Install nodejs
2) Install Electron:
`sudo npm install -g electron-prebuilt --unsafe-perm=true --allow-root`
3) Install Bower:
`npm install -g bower`
4) Clone this repository
`git clone https://github.com/iotaledger/wallet`
5) Go to the wallet directory:
`cd wallet`
6) Clone iri:
git clone https://github.com/iotaledger/iri
7) Download iri-1.2.1.jar from `https://github.com/iotaledger/iri/releases` rename it to iri.jar and save into `~/wallet/iri/` floder
8) sudo npm install
9) npm start

On the step 9 I see the GUI with the above error. Also `sudo npm run compile` show the next error:

```
> iota@2.1.0 precompile /home/alex/wallet
> rimraf out/*


> iota@2.1.0 compile /home/alex/wallet
> export CSC_IDENTITY_AUTO_DISCOVERY=false && build --win --mac --linux --x64 --ia32

Skip app dependencies rebuild because platform is different
Packaging for darwin x64 using electron 1.6.11 to out/mac
Downloading tmp-13666-0-electron-v1.6.11-darwin-x64.zip
[============================================>] 100.0% of 46.08 MB (1.46 MB/s)
⚠️  macOS application code signing is supported only on macOS, skipping.
Building macOS zip
Building DMG
Unhandled rejection Error: spawn hdiutil ENOENT
    at exports._errnoException (util.js:1014:11)                                                                                     
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)                                                        
    at onErrorNT (internal/child_process.js:366:16)                                                                                  
    at _combinedTickCallback (internal/process/next_tick.js:102:11)                                                                  
    at process._tickCallback (internal/process/next_tick.js:161:9)                                                                   
From previous event:                                                                                                                 
    at spawn (/home/alex/wallet/node_modules/electron-builder-util/src/util.ts:97:3)                                                 
    at /home/alex/wallet/node_modules/electron-builder/src/targets/dmg.ts:49:11                                                      
    at Generator.next (<anonymous>)                                                                                                  
    at /home/alex/wallet/node_modules/graceful-fs/graceful-fs.js:99:16                                                               
    at /home/alex/wallet/node_modules/graceful-fs/graceful-fs.js:43:10                                                               
    at FSReqWrap.oncomplete (fs.js:135:15)                                                                                           
From previous event:                                                                                                                 
    at DmgTarget.build (/home/alex/wallet/node_modules/electron-builder/out/targets/dmg.js:234:11)                                   
    at postAsyncTasks.push.default.map.it (/home/alex/wallet/node_modules/electron-builder/src/platformPackager.ts:103:85)           
From previous event:                                                                                                                 
    at MacPackager.packageInDistributableFormat (/home/alex/wallet/node_modules/electron-builder/src/platformPackager.ts:103:41)     
    at /home/alex/wallet/node_modules/electron-builder/src/macPackager.ts:82:26                                                      
From previous event:                                                                                                                 
    at /home/alex/wallet/node_modules/electron-builder/src/macPackager.ts:82:10                                                      
    at Generator.next (<anonymous>)                                                                                                  
From previous event:                                                                                                                 
    at MacPackager.pack (/home/alex/wallet/node_modules/electron-builder/out/macPackager.js:165:11)                                  
    at /home/alex/wallet/node_modules/electron-builder/src/packager.ts:175:22                                                        
From previous event:                                                                                                                 
    at Packager.doBuild (/home/alex/wallet/node_modules/electron-builder/out/packager.js:299:11)                                     
    at /home/alex/wallet/node_modules/electron-builder/src/packager.ts:143:38                                                        
    at Generator.next (<anonymous>)                                                                                                  
    at runCallback (timers.js:800:20)                                                                                                
    at tryOnImmediate (timers.js:762:5)                                                                                              
    at processImmediate [as _immediateCallback] (timers.js:733:5)                                                                    
From previous event:                                                                                                                 
    at Packager.build (/home/alex/wallet/node_modules/electron-builder/out/packager.js:251:11)                                       
    at /home/alex/wallet/node_modules/electron-builder/src/builder.ts:214:40                                                         
    at Generator.next (<anonymous>)                                                                                                  
From previous event:                                                                                                                 
    at build (/home/alex/wallet/node_modules/electron-builder/out/builder.js:63:21)                                                  
    at Object.<anonymous> (/home/alex/wallet/node_modules/electron-builder/out/cli/build-cli.js:68:41)                               
    at Module._compile (module.js:569:30)                                                                                            
    at Object.Module._extensions..js (module.js:580:10)                                                                              
    at Module.load (module.js:503:32)                                                                                                
    at tryModuleLoad (module.js:466:12)                                                                                              
    at Function.Module._load (module.js:458:3)                                                                                       
    at Function.Module.runMain (module.js:605:10)                                                                                    
    at startup (bootstrap_node.js:158:16)                                                                                            
    at bootstrap_node.js:575:3                                                                                                       

Rebuilding native production dependencies for linux:x64
Packaging for linux x64 using electron 1.6.11 to out/linux-unpacked
Unhandled rejection Error: Exit code: ENOENT. spawn icns2png ENOENT
    at /home/alex/wallet/node_modules/electron-builder-util/src/util.ts:75:16
    at exithandler (child_process.js:259:5)
    at ChildProcess.errorhandler (child_process.js:271:5)
    at emitOne (events.js:115:13)
    at ChildProcess.emit (events.js:210:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:195:12)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
From previous event:
    at exec (/home/alex/wallet/node_modules/electron-builder-util/src/util.ts:53:3)
    at /home/alex/wallet/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:136:28
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at LinuxTargetHelper.createFromIcns (/home/alex/wallet/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:186:11)
    at /home/alex/wallet/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:28:25
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/home/alex/wallet/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:58:11)
    at new LinuxTargetHelper (/home/alex/wallet/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:16:23)
    at getHelper (/home/alex/wallet/node_modules/electron-builder/src/linuxPackager.ts:32:18)
    at outDir (/home/alex/wallet/node_modules/electron-builder/src/linuxPackager.ts:61:122)
    at mapper (/home/alex/wallet/node_modules/electron-builder/src/targets/targetFactory.ts:15:16)
    at LinuxPackager.createTargets (/home/alex/wallet/node_modules/electron-builder/src/linuxPackager.ts:61:7)
    at createTargets (/home/alex/wallet/node_modules/electron-builder/src/targets/targetFactory.ts:22:12)
    at /home/alex/wallet/node_modules/electron-builder/src/packager.ts:175:41
From previous event:
    at Packager.doBuild (/home/alex/wallet/node_modules/electron-builder/out/packager.js:299:11)
    at /home/alex/wallet/node_modules/electron-builder/src/packager.ts:143:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Packager.build (/home/alex/wallet/node_modules/electron-builder/out/packager.js:251:11)
    at /home/alex/wallet/node_modules/electron-builder/src/builder.ts:214:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/alex/wallet/node_modules/electron-builder/out/builder.js:63:21)
    at Object.<anonymous> (/home/alex/wallet/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

Building AppImage for arch x64
Building tar.gz
Unhandled rejection Error: Exit code: ENOENT. spawn icns2png ENOENT
    at /home/alex/wallet/node_modules/electron-builder-util/src/util.ts:75:16
    at exithandler (child_process.js:259:5)
    at ChildProcess.errorhandler (child_process.js:271:5)
    at emitOne (events.js:115:13)
    at ChildProcess.emit (events.js:210:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:195:12)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
From previous event:
    at exec (/home/alex/wallet/node_modules/electron-builder-util/src/util.ts:53:3)
    at /home/alex/wallet/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:136:28
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at LinuxTargetHelper.createFromIcns (/home/alex/wallet/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:186:11)
    at /home/alex/wallet/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:28:25
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/home/alex/wallet/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:58:11)
    at new LinuxTargetHelper (/home/alex/wallet/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:16:23)
    at getHelper (/home/alex/wallet/node_modules/electron-builder/src/linuxPackager.ts:32:18)
    at outDir (/home/alex/wallet/node_modules/electron-builder/src/linuxPackager.ts:61:122)
    at mapper (/home/alex/wallet/node_modules/electron-builder/src/targets/targetFactory.ts:15:16)
    at LinuxPackager.createTargets (/home/alex/wallet/node_modules/electron-builder/src/linuxPackager.ts:61:7)
    at createTargets (/home/alex/wallet/node_modules/electron-builder/src/targets/targetFactory.ts:22:12)
    at /home/alex/wallet/node_modules/electron-builder/src/packager.ts:175:41
From previous event:
    at Packager.doBuild (/home/alex/wallet/node_modules/electron-builder/out/packager.js:299:11)
    at /home/alex/wallet/node_modules/electron-builder/src/packager.ts:143:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Packager.build (/home/alex/wallet/node_modules/electron-builder/out/packager.js:251:11)
    at /home/alex/wallet/node_modules/electron-builder/src/builder.ts:214:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/alex/wallet/node_modules/electron-builder/out/builder.js:63:21)
    at Object.<anonymous> (/home/alex/wallet/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

Rebuilding native production dependencies for linux:ia32
Error: /usr/local/bin/node exited with code 1
Output:                                                                                                                              

> ffi@2.2.0 install /home/alex/wallet/node_modules/ffi                                                                               
> node-gyp rebuild                                                                                                                   

make: Entering directory '/home/alex/wallet/node_modules/ffi/build'                                                                  
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o                                                                       
deps/libffi/ffi.target.mk:110: recipe for target 'Release/obj.target/ffi/deps/libffi/src/prep_cif.o' failed                          
make: Leaving directory '/home/alex/wallet/node_modules/ffi/build'                                                                   

Error output:                                                                                                                        
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.electron-gyp/.node-gyp/iojs-1.6.11"               
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/alex/wallet/node_modules/ffi/.node-gyp"                       
In file included from /usr/include/limits.h:25:0,                                                                                    
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/limits.h:168,                                                    
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/syslimits.h:7,                                                   
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/limits.h:34,                                                     
                 from ../deps/libffi/config/linux/ia32/ffi.h:76,                                                                     
                 from ../deps/libffi/src/prep_cif.c:26:                                                                              
/usr/include/features.h:364:25: fatal error: sys/cdefs.h: No such file or directory                                                  
 #  include <sys/cdefs.h>                                                                                                            
                         ^                                                                                                           
compilation terminated.                                                                                                              
make: *** [Release/obj.target/ffi/deps/libffi/src/prep_cif.o] Error 1                                                                
gyp ERR! build error                                                                                                                 
gyp ERR! stack Error: `make` failed with exit code: 2                                                                                
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)                
gyp ERR! stack     at emitTwo (events.js:125:13)                                                                                     
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)                                                                            
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)                                         
gyp ERR! System Linux 4.9.0-3-amd64                                                                                                  
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"             
gyp ERR! cwd /home/alex/wallet/node_modules/ffi                                                                                      
gyp ERR! node -v v8.1.0                                                                                                              
gyp ERR! node-gyp -v v3.6.2                                                                                                          
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-13T21_54_33_234Z-debug.log

    at ChildProcess.childProcess.once.code (/home/alex/wallet/node_modules/electron-builder-util/src/util.ts:134:14)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
From previous event:
    at spawn (/home/alex/wallet/node_modules/electron-builder-util/src/util.ts:97:3)
    at /home/alex/wallet/node_modules/electron-builder/src/yarn.ts:118:11
From previous event:
    at rebuild (/home/alex/wallet/node_modules/electron-builder/out/yarn.js:87:22)
    at /home/alex/wallet/node_modules/electron-builder/src/yarn.ts:16:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at installOrRebuild (/home/alex/wallet/node_modules/electron-builder/out/yarn.js:33:21)
    at /home/alex/wallet/node_modules/electron-builder/src/packager.ts:305:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/home/alex/wallet/node_modules/electron-builder/out/packager.js:403:11)
    at /home/alex/wallet/node_modules/electron-builder/src/packager.ts:168:20
From previous event:
    at Packager.doBuild (/home/alex/wallet/node_modules/electron-builder/out/packager.js:299:11)
    at /home/alex/wallet/node_modules/electron-builder/src/packager.ts:143:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Packager.build (/home/alex/wallet/node_modules/electron-builder/out/packager.js:251:11)
    at /home/alex/wallet/node_modules/electron-builder/src/builder.ts:214:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/alex/wallet/node_modules/electron-builder/out/builder.js:63:21)
    at Object.<anonymous> (/home/alex/wallet/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! iota@2.1.0 compile: `export CSC_IDENTITY_AUTO_DISCOVERY=false && build --win --mac --linux --x64 --ia32`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the iota@2.1.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-13T21_54_33_332Z-debug.log
```

Best regards,
Oleksandr Porunov

**Comment by MaximusMcCann** [comment]
Receiving the same `--headless` error

**Comment by porunov** [comment]
There is no documentation. I don't see normal requirements. There is no required software versions. Also there is no documentation on how to start and use the wallet (full node, lightweight node).

**Comment by atypicalprogrammer** [comment]
You should not be using main branch, only dev branch is up to date (and does not include --headless param). Closing until further notice. If you have any more questions, do reply. Thanks.
