### ISSUE TITLE
Mainnet 2.3.0 mac release issue initializing neighbors

### ISSUE THREAD

**Issue by swyckoff** [iotaledger/wallet#148]
**Issue**
I kept receiving an error (see below) trying to use the gui to add my first neighbor using the IOTA Wallet.app.  IIRC the initial screen I saw after selecting Full Node was not the green seed / password login screen but just a gray box where you add neighbors.

Environment: 

- macOS Sierra 10.12.5 (16F73). 
- jreVersion 1.8.0_131
- appVersion 1.2.0

**Work around**
Launching the IOTA Wallet app with sudo: `sudo open "/Applications/IOTA Wallet.app" `. 

Downsides... sudo is risky business.

**Stacktrace**
```
06/30 02:32:58.832 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.2.0
06/30 02:32:59.399 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database Backend... 
06/30 02:32:59.427 [main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation: 
org.rocksdb.RocksDBException: mainnetdb: Permission denied
    at org.rocksdb.RocksDB.open(Native Method) ~[iri.jar:na]
    at org.rocksdb.RocksDB.open(RocksDB.java:286) ~[iri.jar:na]
    at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.initDB(RocksDBPersistenceProvider.java:494) ~[iri.jar:na]
    at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.init(RocksDBPersistenceProvider.java:71) ~[iri.jar:na]
    at com.iota.iri.storage.Tangle.init(Tangle.java:27) ~[iri.jar:na]
    at com.iota.iri.Iota.init(Iota.java:87) ~[iri.jar:na]
    at com.iota.iri.IRI.main(IRI.java:86) ~[iri.jar:na]
06/30 02:32:59.427 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
06/30 02:33:05.432 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
java.lang.NullPointerException: null
    at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri.jar:na]
    at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri.jar:na]
    at com.iota.iri.Iota.shutdown(Iota.java:164) ~[iri.jar:na]
    at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:253) ~[iri.jar:na]
    at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Process exited with status 255
```

**Comment by arancauchi** [comment]
This looks like a simple permissions error on either the directory, or the mainnet db. Go ahead and check what the permissions are,

**Comment by swyckoff** [comment]
Different issue but on [](https://github.com/iotaledger/wallet/releases) for macOS it says`~/.Library/Application Support/IOTA Wallet` when really it is `~/Library/Application Support/IOTA Wallet` (no '.')

**Comment by swyckoff** [comment]
It wasn't a permission issue afaict. It seems to work when I redownload the 2.3.0 gui (and deleted the old iri dir in the IOTA Wallet dir)
