### ISSUE TITLE
RocksDBException: Failed to create lock file

### ISSUE THREAD

**Issue by kasaram** [iotaledger/wallet#158]
My server restated and after running IOTA full node got got below error.
Windows 2012 server - 64 bit
Full node running from last 5 hours.

07/12 18:35:12.714 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.2.4
07/12 18:35:17.986 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database Backend... 
07/12 18:35:18.208 [main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation: 
org.rocksdb.RocksDBException: Failed to create lock file: mainnetdb/LOCK: The process cannot access the file because it is being used by another process.
	at org.rocksdb.RocksDB.open(Native Method) ~[iri.jar:na]
	at org.rocksdb.RocksDB.open(RocksDB.java:286) ~[iri.jar:na]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.initDB(RocksDBPersistenceProvider.java:498) ~[iri.jar:na]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.init(RocksDBPersistenceProvider.java:71) ~[iri.jar:na]
	at com.iota.iri.storage.Tangle.init(Tangle.java:26) ~[iri.jar:na]
	at com.iota.iri.Iota.init(Iota.java:91) ~[iri.jar:na]
	at com.iota.iri.IRI.main(IRI.java:86) ~[iri.jar:na]
07/12 18:35:18.222 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
07/12 18:35:24.237 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
java.lang.NullPointerException: null
	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri.jar:na]
	at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri.jar:na]
	at com.iota.iri.Iota.shutdown(Iota.java:168) ~[iri.jar:na]
	at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:253) ~[iri.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_131]
Process exited with status 4294967295

**Comment by lueyforje** [comment]
I would get this same error when "IOTA Wallet" process gets terminated, but the "JAVA(TM) Platform SE Binary" is still running in the background. If you terminate this java process as well then you can run iota again.
