### ISSUE TITLE
Initialization Alert

### ISSUE THREAD

**Issue by puck2** [iotaledger/wallet#170]
After install on Windows 10... I had a full node running and even connected to a neighbor via Slack. Then I uninstalled (not sure 100% if I had this error before uninstalling). Upon reinsalling, wallet will not start up, get this error (aybe node is still running in background?):

>Exception occurred shutting down IOTA node:

> 07/23 13:15:36.989 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.2.4
> 07/23 13:15:44.198 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database Backend... 
> 07/23 13:15:44.351 [main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation: 
> org.rocksdb.RocksDBException: Failed to create lock file: mainnetdb/LOCK: The process cannot access the file because it is being used by another process.
> 	at org.rocksdb.RocksDB.open(Native Method) ~[iri.jar:na]
> 	at org.rocksdb.RocksDB.open(RocksDB.java:286) ~[iri.jar:na]
> 	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.initDB(RocksDBPersistenceProvider.java:498) ~[iri.jar:na]
> 	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.init(RocksDBPersistenceProvider.java:71) ~[iri.jar:na]
> 	at com.iota.iri.storage.Tangle.init(Tangle.java:26) ~[iri.jar:na]
> 	at com.iota.iri.Iota.init(Iota.java:91) ~[iri.jar:na]
> 	at com.iota.iri.IRI.main(IRI.java:86) ~[iri.jar:na]
> 07/23 13:15:44.352 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
> 07/23 13:15:50.355 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
> java.lang.NullPointerException: null
> 	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri.jar:na]
> 	at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri.jar:na]
> 	at com.iota.iri.Iota.shutdown(Iota.java:168) ~[iri.jar:na]
> 	at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:253) ~[iri.jar:na]
> 	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_121]
> Process exited with status 4294967295
> 
> 
> 
>

**Comment by puck2** [comment]
OK I see that the Iota task was still running... 4 instances actually

**Comment by puck2** [comment]
I had uninstalled IOTA wallet but the process was still running

**Comment by puck2** [comment]
OK, I killed all Iota processes, tried to reinstall Iota wallet, get the following error:

> 07/23 13:22:17.725 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.2.4
> 07/23 13:22:18.955 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database Backend... 
> 07/23 13:22:19.103 [main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation: 
> org.rocksdb.RocksDBException: Failed to create lock file: mainnetdb/LOCK: The process cannot access the file because it is being used by another process.
> 	at org.rocksdb.RocksDB.open(Native Method) ~[iri.jar:na]
> 	at org.rocksdb.RocksDB.open(RocksDB.java:286) ~[iri.jar:na]
> 	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.initDB(RocksDBPersistenceProvider.java:498) ~[iri.jar:na]
> 	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.init(RocksDBPersistenceProvider.java:71) ~[iri.jar:na]
> 	at com.iota.iri.storage.Tangle.init(Tangle.java:26) ~[iri.jar:na]
> 	at com.iota.iri.Iota.init(Iota.java:91) ~[iri.jar:na]
> 	at com.iota.iri.IRI.main(IRI.java:86) ~[iri.jar:na]
> 07/23 13:22:19.105 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
> 07/23 13:22:25.111 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
> java.lang.NullPointerException: null
> 	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri.jar:na]
> 	at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri.jar:na]
> 	at com.iota.iri.Iota.shutdown(Iota.java:168) ~[iri.jar:na]
> 	at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:253) ~[iri.jar:na]
> 	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_121]
> Process exited with status 4294967295

**Comment by puck2** [comment]
Uninstalled Iota Wallet and tried to reinstall, same error. I'll try restarting and see if that helps...

**Comment by puck2** [comment]
restarted and deleted both (iota and IOTA wallet) appdata folders and was able to reinstall successfully
