### ISSUE TITLE
JavaScript error when starting first time

### ISSUE THREAD

**Issue by meinharrd** [iotaledger/wallet#396]
When launching the wallet for the first time (data folder `~/.Library/Application Support/IOTA Wallet` removed), I get this error:

```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: template[1].submenu.splce is not a function
    at Object.App.createMenuBar (/Applications/IOTA Wallet.app/Contents/Resources/app.asar/app/js/main.js:584:27)
    at Object.App.showWindow (/Applications/IOTA Wallet.app/Contents/Resources/app.asar/app/js/main.js:1978:9)
    at Object.App.showSetupWindow (/Applications/IOTA Wallet.app/Contents/Resources/app.asar/app/js/main.js:1800:9)
    at Object.App.start (/Applications/IOTA Wallet.app/Contents/Resources/app.asar/app/js/main.js:1017:11)
    at Object.App.initialize (/Applications/IOTA Wallet.app/Contents/Resources/app.asar/app/js/main.js:113:9)
    at App.<anonymous> (/Applications/IOTA Wallet.app/Contents/Resources/app.asar/app/js/main.js:2473:7)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
```

Screenshot:

![screen shot 2017-10-25 at 10 55 10](https://user-images.githubusercontent.com/396346/31990631-f433c8ce-b975-11e7-8f94-317801220928.png)

Functionality does not seem to be harmed, yet it looks a little terrifying. 😱

Environment:
 * IOTA Wallet v2.5.2
 * MacOS 10.13

**Comment by puzanov** [comment]
Same issue. Occurs on fresh install and first run.

**Comment by wonkytonky** [comment]
![image](https://user-images.githubusercontent.com/19390834/31998092-cf539a48-b98e-11e7-8495-58a21c66eb4f.png)

from a friend of mine.. 

errors happend on first use. 

errors also don't look problematic .. but it would be nice to not have them ;)

**Comment by Raindal** [comment]
Same error here, on OS X 10.11.6 wallet 2.5.2
