### ISSUE TITLE
Wallet v2.2.0 is unuseable

### ISSUE THREAD

**Issue by pinpong** [iotaledger/wallet#40]
Mac OSx Sierra.

```
ccurl-interface.js:67 Uncaught TypeError: Cannot read property 'isHash' of undefined
    at Object.ccurlHashing (/Applications/IOTA Wallet.app/Contents/Resources/app.asar/app/js/ccurl-interface.js:67:20)
    at api.iota.api.attachToTangle (eval at globalEval (file:///Applications/IOTA%20Wallet.app/Contents/Resources/ui/bower_components/jquery/dist/jquery.min.js:1:1), <anonymous>:4:11)
    at file:///Applications/IOTA%20Wallet.app/Contents/Resources/ui/bower_components/iota.lib.js/dist/iota.js:679:14
    at file:///Applications/IOTA%20Wallet.app/Contents/Resources/ui/bower_components/iota.lib.js/dist/iota.js:434:20
    at file:///Applications/IOTA%20Wallet.app/Contents/Resources/ui/bower_components/iota.lib.js/dist/iota.js:38:20
    at makeRequest.prepareResult (file:///Applications/IOTA%20Wallet.app/Contents/Resources/ui/bower_components/iota.lib.js/dist/iota.js:3679:10)
    at exports.XMLHttpRequest.request.onreadystatechange (file:///Applications/IOTA%20Wallet.app/Contents/Resources/ui/bower_components/iota.lib.js/dist/iota.js:3636:23)
    at exports.XMLHttpRequest.dispatchEvent (file:///Applications/IOTA%20Wallet.app/Contents/Resources/ui/bower_components/iota.lib.js/dist/iota.js:17038:25)
    at setState (file:///Applications/IOTA%20Wallet.app/Contents/Resources/ui/bower_components/iota.lib.js/dist/iota.js:17057:14)
    at exports.IncomingMessage.<anonymous> (file:///Applications/IOTA%20Wallet.app/Contents/Resources/ui/bower_components/iota.lib.js/dist/iota.js:16894:13)
@ ccurl-interface.js:67iota.api.attachToTangle 
@ VM124:4(anonymous function) 
@ iota.js:679(anonymous function) 
@ iota.js:434(anonymous function) 
@ iota.js:38makeRequest.prepareResult 
@ iota.js:3679request.onreadystatechange 
@ iota.js:3636dispatchEvent 
@ iota.js:17038setState 
@ iota.js:17057(anonymous function) 
@ iota.js:16894EventEmitter.emit 
@ iota.js:11593endReadableNT 
@ iota.js:13933afterTickTwo 
@ iota.js:11986Item.run 
@ iota.js:12158drainQueue 
@ iota.js:12128
```

**Comment by domschiener** [comment]
Fixed
