### ISSUE TITLE
Node v9 compilation issue

### ISSUE THREAD

**Issue by yannickl** [iotaledger/wallet#448]
Hi there,

I can't compile the client with Node v9.1 because of deprecated APIs. I'm on macOS v10.13.1.

Here is the log:
```log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.5.1
3 info using node@v9.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle iota@2.5.4~prestart: iota@2.5.4
6 info lifecycle iota@2.5.4~start: iota@2.5.4
7 verbose lifecycle iota@2.5.4~start: unsafe-perm in lifecycle true
8 verbose lifecycle iota@2.5.4~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/****/iotawallet/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/usr/local/git/bin:/Users/****/bin
9 verbose lifecycle iota@2.5.4~start: CWD: /Users/****/iotawallet
10 silly lifecycle iota@2.5.4~start: Args: [ '-c',
10 silly lifecycle   'export NODE_ENV=development || set NODE_ENV=development && electron app/js/main.js' ]
11 silly lifecycle iota@2.5.4~start: Returned: code: 1  signal: null
12 info lifecycle iota@2.5.4~start: Failed to exec start script
13 verbose stack Error: iota@2.5.4 start: `export NODE_ENV=development || set NODE_ENV=development && electron app/js/main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:135:13)
13 verbose stack     at EventEmitter.emit (events.js:224:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:135:13)
13 verbose stack     at ChildProcess.emit (events.js:224:7)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid iota@2.5.4
15 verbose cwd /Users/****/iotawallet
16 verbose Darwin 17.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v9.1.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error iota@2.5.4 start: `export NODE_ENV=development || set NODE_ENV=development && electron app/js/main.js`
22 error Exit status 1
23 error Failed at the iota@2.5.4 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Btw thank you for your great job!

**Comment by eaigner** [comment]
I second this
