### ISSUE TITLE
Issue when I am accessing Jar File

### ISSUE THREAD

**Issue by shazeltion17** [iotaledger/wallet#561]
Hi there,  I have an issue when I run the:

java -jar iri.jar -p 14600 command.

I get the following output on my ec2 linux installation.  

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/iota/iri/IRI : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

java version looks like this:

 java -version
java version "1.7.0_151"
OpenJDK Runtime Environment (amzn-2.6.11.0.74.amzn1-x86_64 u151-b00)
OpenJDK 64-Bit Server VM (build 24.151-b00, mixed mode)

I have java installed and all the right things have occurred.  Can you please help me understand why this isn't working as I would expect?

**Comment by wonkytonky** [comment]
try 1.8 java oracle
