### ISSUE TITLE
Error message after adding neighbors

### ISSUE THREAD

**Issue by tristanturner** [iotaledger/wallet#67]
05/31 19:20:49.079 [XNIO-1 task-1] ERROR com.iota.iri.service.API - API Exception: 
java.lang.NullPointerException: null
	at com.iota.iri.network.Neighbor.<init>(Neighbor.java:45) ~[iri.jar:na]
	at com.iota.iri.network.UDPNeighbor.<init>(UDPNeighbor.java:19) ~[iri.jar:na]
	at com.iota.iri.service.API.addNeighborsStatement(API.java:761) [iri.jar:na]
	at com.iota.iri.service.API.process(API.java:181) [iri.jar:na]
	at com.iota.iri.service.API.processRequest(API.java:147) [iri.jar:na]
	at com.iota.iri.service.API.access$000(API.java:81) [iri.jar:na]
	at com.iota.iri.service.API$1.handleRequest(API.java:135) [iri.jar:na]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [iri.jar:na]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [iri.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_92]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_92]
05/31 19:20:55.559 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 3 , toRequest = 238 , toReply = 0 / totalTransactions = 276954

When trying to add a neighbor, the following messages appear:
"Error whilst adding neighbors"
"An API exception occurred"

Neighbors are still added into the "Edit Neighbors" list and the neighbors are visible in the "View Neighbors" list after restarting.

**Comment by atypicalprogrammer** [comment]
@domschiener did u investigate the neighbor issue yet?

**Comment by domschiener** [comment]
Resolved.
