### ISSUE TITLE
ERROR running wallet first time: NoClassDefFoundError

### ISSUE THREAD

**Issue by bulrush15** [iotaledger/wallet#710]
I installed the Iota full GUI node from Github. The file I used was  IOTA.Wallet.Setup.2.5.4.exe on Windows 8. I also installed JDK 9.0.1,  and set up the path to Java in Control panel, and rebooted the PC. I  copied the IRI.jar file to the iri directory, and when I start the Iota  GUI node I get this error:

    12/07 05:07:10.000 [main] INFO com.iota.iri.IRI - 

    Welcome to IRI 1.4.1.3Exception in thread "main"java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException  at com.iota.iri.IRI.main(IRI.java:55)  Caused by: java.lang.ClassNotFoundException: 

    javax.xml.bind.ValidationException  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)  at java.base/java.lang.ClassLoader.loadClass(Unknown Source)

    ... 1 more  Process exited with status 1

Any ideas how to fix this? Are there other system variables I'm supposed to set up? 

I can't set up any nodes because I get this error. 

Thank you. I'm trying to set up a full node to help the community.

**Comment by wonkytonky** [comment]
try java 8

**Comment by bulrush15** [comment]
Should I install the JRE or JDK?
