### ISSUE TITLE
Wallet will not start

### ISSUE THREAD

**Issue by tristanturner** [iotaledger/wallet#72]
Had the gui wallet running on a full node for about 24 hours. Restarted the wallet and now get this error upon start:

06/02 17:49:34.684 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.1.4
06/02 17:49:36.406 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database Backend... 
06/02 17:49:36.517 [main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation: 
org.rocksdb.RocksDBException: Failed to create lock file: mainnetdb/LOCK: The process cannot access the file because it is being used by another process.
    at org.rocksdb.RocksDB.open(Native Method) ~[iri.jar:na]
    at org.rocksdb.RocksDB.open(RocksDB.java:286) ~[iri.jar:na]
    at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.initDB(RocksDBPersistenceProvider.java:492) ~[iri.jar:na]
    at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.init(RocksDBPersistenceProvider.java:71) ~[iri.jar:na]
    at com.iota.iri.storage.Tangle.init(Tangle.java:27) ~[iri.jar:na]
    at com.iota.iri.Iota.init(Iota.java:77) ~[iri.jar:na]
    at com.iota.iri.IRI.main(IRI.java:86) ~[iri.jar:na]
06/02 17:49:36.520 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
06/02 17:49:42.524 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
java.lang.NullPointerException: null
    at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri.jar:na]
    at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri.jar:na]
    at com.iota.iri.Iota.shutdown(Iota.java:92) ~[iri.jar:na]
    at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:248) ~[iri.jar:na]
    at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_92]
Process exited with status 4294967295

**Comment by atypicalprogrammer** [comment]
Do you get a nice GUI error dialog or only a command line error? What system?

**Comment by domschiener** [comment]
Related to another IRI process running in thee background (perhaps you did not shut it down properly?)
