### ISSUE TITLE
UnsatisfiedLinkError when starting IRI in GUI

### ISSUE THREAD

**Issue by Jehoel** [iotaledger/wallet#773]
I'm running the `IOTA Wallet.exe` version 2.5.3.0 on Windows 10 x64 Build 16299.125.

I downloaded the Mainnet IRI 1.4.1.2 `*.jar` file.

I installed Java 9, then experienced this issue: https://github.com/iotaledger/wallet/issues/437 - so I installed Java 8u152 then uninstalled Java 9.

IRI refuses to start inside the GUI and this error message is displayed in the GUI Server Output window:

```
12/16 08:43:24.228 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.2
Exception in thread "main" 
java.lang.UnsatisfiedLinkError: C:\Users\Me\AppData\Local\Temp\librocksdbjni9021065064317411549.dll: A dynamic link library (DLL) initialization routine failed
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)
	at com.iota.iri.Iota.initializeTangle(Iota.java:203)
	at com.iota.iri.Iota.init(Iota.java:94)
	at com.iota.iri.IRI.main(IRI.java:86)
12/16 08:43:49.133 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
12/16 08:43:55.158 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
java.lang.NullPointerException: null
	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri.jar:na]
	at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri.jar:na]
	at com.iota.iri.Iota.shutdown(Iota.java:178) ~[iri.jar:na]
	at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:253) ~[iri.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_152]
Process exited with status 1
```

Some quick googling suggested the issue might be a missing VisualC++ 2015 redistributable - however I have both the x86 and x64 versions installed.

**Comment by Jehoel** [comment]
This issue looks similar, but they have a different exception message: https://github.com/iotaledger/iri/issues/390
