### ISSUE TITLE
Error during wallet installation on Linux

### ISSUE THREAD

**Issue by pippo111** [iotaledger/wallet#850]
I got error message during `npm install`

- ArchLinux
- npm v5.6.0
- node v9.2.0
- electron v1.7.10

Here is full debug log:

```
npm install

> ref@1.3.5 install /home/filip/Dokumenty/iota/wallet/node_modules/ref
> node-gyp rebuild

make: Wejście do katalogu '/home/filip/Dokumenty/iota/wallet/node_modules/ref/build'
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../../nan/nan.h:192:0,
                 from ../src/binding.cc:7:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:112:73: warning: ‘v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
                                                                         ^
In file included from /home/filip/.node-gyp/9.2.0/include/node/v8.h:26:0,
                 from /home/filip/.node-gyp/9.2.0/include/node/node.h:63,
                 from ../src/binding.cc:5:
/home/filip/.node-gyp/9.2.0/include/node/v8.h:3115:29: note: declared here
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/filip/.node-gyp/9.2.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Opuszczenie katalogu '/home/filip/Dokumenty/iota/wallet/node_modules/ref/build'

> ffi@2.2.0 install /home/filip/Dokumenty/iota/wallet/node_modules/ffi
> node-gyp rebuild

make: Wejście do katalogu '/home/filip/Dokumenty/iota/wallet/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
../deps/libffi/src/x86/ffi64.c: In function ‘classify_argument’:
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
    FFI_ASSERT (0);
                  ^
../deps/libffi/src/x86/ffi64.c:156:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       {
       ^
../deps/libffi/src/x86/ffi64.c:183:5: note: here
     case FFI_TYPE_FLOAT:
     ^~~~
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/sysv.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
In file included from ../../nan/nan.h:192:0,
                 from ../src/ffi.h:23,
                 from ../src/ffi.cc:3:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:112:73: warning: ‘v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
                                                                         ^
In file included from /home/filip/.node-gyp/9.2.0/include/node/v8.h:26:0,
                 from /home/filip/.node-gyp/9.2.0/include/node/node.h:63,
                 from ../src/ffi.cc:1:
/home/filip/.node-gyp/9.2.0/include/node/v8.h:3115:29: note: declared here
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/filip/.node-gyp/9.2.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/ffi.cc: In static member function ‘static void FFI::InitializeBindings(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/ffi.cc:111:153: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, v8::Local<v8::Value>, v8::PropertyAttribute)’
 LocalChecked(), WrapPointer((char *)RTLD_NEXT), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                                      ^
In file included from /home/filip/.node-gyp/9.2.0/include/node/v8.h:26:0,
                 from /home/filip/.node-gyp/9.2.0/include/node/node.h:63,
                 from ../src/ffi.cc:1:
/home/filip/.node-gyp/9.2.0/include/node/v8.h:3115:29: note: candidate: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/filip/.node-gyp/9.2.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/filip/.node-gyp/9.2.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/filip/.node-gyp/9.2.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/ffi.cc:114:159: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, v8::Local<v8::Value>, v8::PropertyAttribute)’
 alChecked(), WrapPointer((char *)RTLD_DEFAULT), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                                      ^
In file included from /home/filip/.node-gyp/9.2.0/include/node/v8.h:26:0,
                 from /home/filip/.node-gyp/9.2.0/include/node/node.h:63,
                 from ../src/ffi.cc:1:
/home/filip/.node-gyp/9.2.0/include/node/v8.h:3115:29: note: candidate: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/filip/.node-gyp/9.2.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/filip/.node-gyp/9.2.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/filip/.node-gyp/9.2.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/ffi.cc:123:167: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Uint32>::return_t, v8::PropertyAttribute)’
 d(), Nan::New<Uint32>((uint32_t)sizeof(ffi_arg)), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
                                                                                                      ^
In file included from /home/filip/.node-gyp/9.2.0/include/node/v8.h:26:0,
                 from /home/filip/.node-gyp/9.2.0/include/node/node.h:63,
                 from ../src/ffi.cc:1:
/home/filip/.node-gyp/9.2.0/include/node/v8.h:3115:29: note: candidate: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/filip/.node-gyp/9.2.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/filip/.node-gyp/9.2.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/filip/.node-gyp/9.2.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/ffi.cc:124:171: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Uint32>::return_t, v8::PropertyAttribute)’
 , Nan::New<Uint32>((uint32_t)sizeof(ffi_sarg)), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                                      ^
In file included from /home/filip/.node-gyp/9.2.0/include/node/v8.h:26:0,
                 from /home/filip/.node-gyp/9.2.0/include/node/node.h:63,
                 from ../src/ffi.cc:1:
/home/filip/.node-gyp/9.2.0/include/node/v8.h:3115:29: note: candidate: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/filip/.node-gyp/9.2.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/filip/.node-gyp/9.2.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/filip/.node-gyp/9.2.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/ffi.cc:125:171: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Uint32>::return_t, v8::PropertyAttribute)’
 , Nan::New<Uint32>((uint32_t)sizeof(ffi_type)), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                                      ^
In file included from /home/filip/.node-gyp/9.2.0/include/node/v8.h:26:0,
                 from /home/filip/.node-gyp/9.2.0/include/node/node.h:63,
                 from ../src/ffi.cc:1:
/home/filip/.node-gyp/9.2.0/include/node/v8.h:3115:29: note: candidate: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/filip/.node-gyp/9.2.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/filip/.node-gyp/9.2.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/filip/.node-gyp/9.2.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/ffi.cc:126:169: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Uint32>::return_t, v8::PropertyAttribute)’
 ), Nan::New<Uint32>((uint32_t)sizeof(ffi_cif)), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                                      ^
In file included from /home/filip/.node-gyp/9.2.0/include/node/v8.h:26:0,
                 from /home/filip/.node-gyp/9.2.0/include/node/node.h:63,
                 from ../src/ffi.cc:1:
/home/filip/.node-gyp/9.2.0/include/node/v8.h:3115:29: note: candidate: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/filip/.node-gyp/9.2.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/filip/.node-gyp/9.2.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/filip/.node-gyp/9.2.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/ffi.cc:132:148: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t, v8::PropertyAttribute)’
 ).ToLocalChecked(), Nan::New<Boolean>(hasObjc), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                                      ^
In file included from /home/filip/.node-gyp/9.2.0/include/node/v8.h:26:0,
                 from /home/filip/.node-gyp/9.2.0/include/node/node.h:63,
                 from ../src/ffi.cc:1:
/home/filip/.node-gyp/9.2.0/include/node/v8.h:3115:29: note: candidate: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/filip/.node-gyp/9.2.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/filip/.node-gyp/9.2.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/filip/.node-gyp/9.2.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
make: *** [ffi_bindings.target.mk:104: Release/obj.target/ffi_bindings/src/ffi.o] Błąd 1
make: Opuszczenie katalogu '/home/filip/Dokumenty/iota/wallet/node_modules/ffi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.14.3-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/filip/Dokumenty/iota/wallet/node_modules/ffi
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.1 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/filip/.npm/_logs/2017-12-22T23_03_08_334Z-debug.log

```
I also attached full debug log. Please help.
[2017-12-22T23_03_08_334Z-debug.log](https://github.com/iotaledger/wallet/files/1583655/2017-12-22T23_03_08_334Z-debug.log)

**Comment by mnlfischer** [comment]
+1

**Comment by hpr** [comment]
I'm also experiencing this error on GNU/Linux, npm 5.6.0, nodejs 9.4.0

**Comment by hpr** [comment]
I fixed it by installing the LTS release of nodejs + npm, v8.9.4.

**Comment by amosonn** [comment]
Here with `npm install ffi`. Also arch (in node docker container), node 9.4.0, npm 5.6.0, nodegyp 3.6.2.
