### ISSUE TITLE
Error Compiling IOTA Wallet

### ISSUE THREAD

**Issue by swdevMPaul** [iotaledger/wallet#953]
Hi,

I have installed Docker, Electron, npm, Nodejs succ. on Ubuntu 16.04, now when I compile the wallet:

root@paul-Inspiron-N7010:/home/paul/IOTA_DEV/wallet# sudo npm run compile:lin

> iota@2.5.6 compile:lin /home/paul/IOTA_DEV/wallet
> electron-builder --linux --x64 --ia32

electron-builder 19.37.2
Rebuilding native production dependencies for linux:x64
Packaging for linux x64 using electron 1.7.9 to out/linux-unpacked
Unhandled rejection Error: Exit code: ENOENT. spawn icns2png ENOENT
    at /home/paul/IOTA_DEV/wallet/node_modules/builder-util/src/util.ts:116:16
    at exithandler (child_process.js:279:5)
    at ChildProcess.errorhandler (child_process.js:291:5)
    at ChildProcess.emit (events.js:159:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
From previous event:
    at exec (/home/paul/IOTA_DEV/wallet/node_modules/builder-util/src/util.ts:84:3)
    at /home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:193:28
    at Generator.next (<anonymous>)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at LinuxTargetHelper.createFromIcns (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:236:11)
    at /home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:58:25
    at Generator.next (<anonymous>)
    at FSReqWrap.oncomplete (fs.js:149:20)
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:88:11)
    at new LinuxTargetHelper (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:23:23)
    at getHelper (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/linuxPackager.ts:33:18)
    at outDir (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/linuxPackager.ts:62:122)
    at mapper (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/targets/targetFactory.ts:49:16)
    at LinuxPackager.createTargets (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/linuxPackager.ts:62:7)
    at createTargets (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/targets/targetFactory.ts:56:12)
    at /home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/packager.ts:240:28
From previous event:
    at Packager.doBuild (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/out/packager.js:344:11)
    at /home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/out/packager.js:263:11)
    at /home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/builder.ts:283:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/out/builder.js:63:21)
    at then (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/cli/cli.ts:48:4)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at Object.args [as handler] (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/cli/cli.ts:48:4)
    at Object.runCommand (/home/paul/IOTA_DEV/wallet/node_modules/yargs/lib/command.js:226:22)
    at Object.parseArgs [as _parseArgs] (/home/paul/IOTA_DEV/wallet/node_modules/yargs/yargs.js:998:24)
    at Object.get [as argv] (/home/paul/IOTA_DEV/wallet/node_modules/yargs/yargs.js:912:21)
    at Object.<anonymous> (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

Building AppImage for arch x64
Building tar.gz
Rebuilding native production dependencies for linux:ia32
Error: /usr/bin/node exited with code 1
Output:

> ffi@2.2.0 install /home/paul/IOTA_DEV/wallet/node_modules/ffi
> node-gyp rebuild

make: Entering directory '/home/paul/IOTA_DEV/wallet/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
deps/libffi/ffi.target.mk:110: recipe for target 'Release/obj.target/ffi/deps/libffi/src/prep_cif.o' failed
make: Leaving directory '/home/paul/IOTA_DEV/wallet/node_modules/ffi/build'

Error output:
In file included from /usr/include/limits.h:25:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/limits.h:168,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/limits.h:34,
                 from ../deps/libffi/config/linux/ia32/ffi.h:76,
                 from ../deps/libffi/src/prep_cif.c:26:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/ffi/deps/libffi/src/prep_cif.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.4.0-104-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/paul/IOTA_DEV/wallet/node_modules/ffi
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-04T11_45_45_832Z-debug.log

    at ChildProcess.childProcess.once.code (/home/paul/IOTA_DEV/wallet/node_modules/builder-util/src/util.ts:227:14)
    at Object.onceWrapper (events.js:254:19)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
From previous event:
    at spawn (/home/paul/IOTA_DEV/wallet/node_modules/builder-util/src/util.ts:190:3)
    at /home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/util/yarn.ts:175:5
From previous event:
    at rebuild (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/out/util/yarn.js:96:22)
    at /home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/util/yarn.ts:21:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at installOrRebuild (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/out/util/yarn.js:34:21)
    at /home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/packager.ts:338:7
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/out/packager.js:408:11)
    at /home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/packager.ts:234:20
From previous event:
    at Packager.doBuild (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/out/packager.js:344:11)
    at /home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/out/packager.js:263:11)
    at /home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/builder.ts:283:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/out/builder.js:63:21)
    at then (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/cli/cli.ts:48:4)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at Object.args [as handler] (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/cli/cli.ts:48:4)
    at Object.runCommand (/home/paul/IOTA_DEV/wallet/node_modules/yargs/lib/command.js:226:22)
    at Object.parseArgs [as _parseArgs] (/home/paul/IOTA_DEV/wallet/node_modules/yargs/yargs.js:998:24)
    at Object.get [as argv] (/home/paul/IOTA_DEV/wallet/node_modules/yargs/yargs.js:912:21)
    at Object.<anonymous> (/home/paul/IOTA_DEV/wallet/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! iota@2.5.6 compile:lin: `electron-builder --linux --x64 --ia32`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the iota@2.5.6 compile:lin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-04T11_45_45_964Z-debug.log

Please help. Why such error and how to fix it ?

Kind Regards.

**Comment by upeksha1996** [comment]
did you find any solution for this?
